name: steam
favicon: null
layout_spectrum: 0.6805833242833614
typography_spectrum: 0.955871171085164
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6629520782735199
  lightness: 0.26881200540810823
  saturation: 0.3473578777629882
  rhythmicContrast: 0.9255405534058809
purpose: []
